# Generated by Django 2.2.10 on 2020-03-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usrId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('channelId', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['usrId'],
            },
        ),
    ]
