# Generated by Django 2.2.10 on 2020-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=30)),
                ('comment_id', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('like', models.IntegerField()),
                ('author_name', models.CharField(max_length=30)),
                ('author_image', models.CharField(max_length=50)),
                ('timestamp', models.BooleanField(default=False)),
                ('class3', models.IntegerField()),
                ('class6', models.IntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['video_id', '-like'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('video_id', models.CharField(max_length=30)),
                ('parent_id', models.CharField(max_length=30)),
                ('comment_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=30)),
                ('author_image', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['video_id', 'parent_id'],
            },
        ),
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class3', models.IntegerField()),
                ('class6', models.IntegerField()),
            ],
        ),
    ]
