# Generated by Django 2.2.10 on 2020-03-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('video_id', 'comment_id')},
        ),
    ]
