# Generated by Django 2.2.10 on 2020-03-05 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20200305_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Comment'),
        ),
    ]
