# Generated by Django 2.2.10 on 2020-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20200305_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='parent_id',
            field=models.CharField(max_length=30),
        ),
    ]
